-- CODE_FILE_OPER 表添加 DATASOURCE_CODE 字段
-- 用于关联 CONFIG_PULL_DATASOURCE 表的动态数据源配置
-- 请根据实际数据库类型选择执行

-- Oracle / OceanBase Oracle 模式
-- ALTER TABLE CODE_FILE_OPER ADD DATASOURCE_CODE VARCHAR2(32);
-- COMMENT ON COLUMN CODE_FILE_OPER.DATASOURCE_CODE IS '动态数据源编码，关联CONFIG_PULL_DATASOURCE';

-- MySQL / OceanBase MySQL 模式
ALTER TABLE code_file_oper ADD COLUMN datasource_code VARCHAR(32) DEFAULT NULL COMMENT '动态数据源编码，关联CONFIG_PULL_DATASOURCE';
