-- CODE_FILE_OPER 表增加 5 个字段（Oracle）
-- 1) file_list_shell 开关  2) 上传/下载前 Groovy  3) 前 Groovy 开关
-- 4) 上传/下载成功后 Groovy  5) 后 Groovy 开关

ALTER TABLE CODE_FILE_OPER ADD (
  FILE_LIST_SHELL_ENABLE       NUMBER(1) DEFAULT 1 NOT NULL,
  FILE_OPER_GROOVY_BEFORE      CLOB,
  FILE_OPER_GROOVY_BEFORE_ENABLE NUMBER(1) DEFAULT 0 NOT NULL,
  FILE_OPER_GROOVY_AFTER       CLOB,
  FILE_OPER_GROOVY_AFTER_ENABLE NUMBER(1) DEFAULT 0 NOT NULL
);

COMMENT ON COLUMN CODE_FILE_OPER.FILE_LIST_SHELL_ENABLE IS '是否执行 FILE_LIST_SHELL：0 否 1 是（为 1 且 FILE_LIST_SHELL 非空时走 Shell 列文件）';
COMMENT ON COLUMN CODE_FILE_OPER.FILE_OPER_GROOVY_BEFORE IS 'SFTP 上传/下载前执行的 Groovy 脚本';
COMMENT ON COLUMN CODE_FILE_OPER.FILE_OPER_GROOVY_BEFORE_ENABLE IS '是否执行前置 Groovy：0 否 1 是';
COMMENT ON COLUMN CODE_FILE_OPER.FILE_OPER_GROOVY_AFTER IS 'SFTP 上传/下载成功后执行的 Groovy 脚本';
COMMENT ON COLUMN CODE_FILE_OPER.FILE_OPER_GROOVY_AFTER_ENABLE IS '是否执行后置 Groovy：0 否 1 是';
